#! /bin/sh

cd /tmp/libcaml-grew
tar -xf libcaml-grew-@VERSION@.tar.gz
cd libcaml-grew-@VERSION@
./configure > log.install
make >> log.install
make uninstall >> log.install
make install >> log.install	
cd ..
rm -rf libcaml-grew-@VERSION@
